<a href="https://colab.research.google.com/github/Netro993/datasci/blob/master/intr0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print("hellp")

In [0]:
import numpy as np
np.__version__

In [0]:
dir(np)

In [0]:
help(np.array)

In [0]:
x = np.array([[1, 3], [2, 5]])
x

In [0]:
x.shape

In [0]:
x.dtype

In [0]:
x.ndim

In [0]:


A = np.array([3, 4, 1, 2])
B = np.array([5, 2, 7, 1])
print(A)
print(B)

In [0]:
A + B

In [0]:
np.exp(1)

In [0]:
np.all([2, 3, 1])

In [0]:
A = np.random.rand(5)
A

In [0]:
np.argmax(A)

In [0]:
A[np.argmax(A)]

In [9]:
np.argsort(A)

array([3, 0, 1, 4, 2])

In [10]:
A[np.argsort(A)]

array([0.17908984, 0.38748871, 0.62795023, 0.87556292, 0.92289295])

In [11]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [0]:
for item in A.flat:
  print(item)

In [15]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [29]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [30]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])